services:
  minio:
    image: quay.io/minio/aistor/minio:latest
    container_name: aistor-server-test
    restart: unless-stopped
    ports:
      - "9000:9000" 
      - "9001:9001"  
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_KMS_SECRET_KEY=my-master-key:0lMFx0poBC7HzsvE4zV/UhPKOFIy0pEf1aF8TjYmaHM=
    volumes:
      - /home/wa/minio/data:/mnt/data
      - /home/wa/minio/certs:/etc/minio/certs
      - /home/wa/minio/minio.license:/minio.license
    command: 
      server /mnt/data 
      --console-address ":9001" 
      --license /minio.license 
      --certs-dir /etc/minio/certs
